/* eslint-disable */
// prettier-ignore
// This file is automatically generated by typings-for-css-modules.
// Don't change it directly!

declare namespace StylesScssModule {
  export interface IStylesScss {
    'borderedRow': string;
    'footer': string;
    'headerRow': string;
    'headerRowWrapper': string;
    'placeholderOverlay': string;
    'row__action-button': string;
    'scrollIconBox': string;
    'sortIconWrapper': string;
    'table': string;
  }
}

declare const StylesScssModule: StylesScssModule.IStylesScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StylesScssModule.IStylesScss;
};

export = StylesScssModule;
