/* eslint-disable */
// prettier-ignore
// This file is automatically generated by typings-for-css-modules.
// Don't change it directly!

declare namespace StylesScssModule {
  export interface IStylesScss {
    'cellPadding': string;
    'focusable': string;
    'footer': string;
    'header': string;
    'headerLeftGap': string;
    'margin': string;
    'pagination': string;
    'row': string;
    'rowContent': string;
    'scrollInner': string;
    'settingIcon': string;
    'sortIconWrapper': string;
    'sortIndex': string;
    'verticalSeparator': string;
    'wrapper': string;
    'zLayerContainer': string;
    'zLayerControl': string;
    'zLayerFix': string;
    'zLayerFluid': string;
    'zLayerMessage': string;
    'zLayerModal': string;
    'zLayerSidebar': string;
    'zLayerSpecific_element': string;
    'zLayerSpecific_element_accent': string;
    'zLayerSubmenu': string;
    'zLayerTopline': string;
  }
}

declare const StylesScssModule: StylesScssModule.IStylesScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StylesScssModule.IStylesScss;
};

export = StylesScssModule;
