import type { StatementHistoryRow } from 'interfaces/admin';
import { locale } from 'localization';
import { accessor, addMaxWidthField } from 'utils/common';
import {
  AccountNumbers,
  Actions,
  CreatedAt,
  Format,
  Organizations,
  RequestPeriod,
  RequestStatus,
  User,
  StatementType,
  StatementStatus,
  ServiceBranches,
} from './cells';
import { COLUMN_NAMES } from './constants';

/** Конфигурация колонок таблицы "История запросов выписок". */
export const columns = addMaxWidthField<StatementHistoryRow, { isVisible: boolean }>([
  {
    Cell: CreatedAt,
    Header: locale.admin.historyScroller.table.header.createdAt,
    accessor,
    id: COLUMN_NAMES.CREATED_AT,
    isVisible: true,
    maxWidth: 120,
    minWidth: 95,
    width: 110,
  },
  {
    Cell: AccountNumbers,
    Header: locale.admin.historyScroller.table.header.accountNumber,
    accessor,
    disableSortBy: true,
    id: COLUMN_NAMES.ACCOUNT_NUMBERS,
    isVisible: true,
    maxWidth: 340,
    minWidth: 150,
    width: 290,
  },
  {
    Cell: Organizations,
    Header: locale.admin.historyScroller.table.header.organization,
    accessor,
    disableSortBy: true,
    id: COLUMN_NAMES.ORGANIZATIONS,
    isVisible: true,
    maxWidth: 340,
    minWidth: 150,
    width: 240,
  },
  {
    Cell: RequestPeriod,
    Header: locale.admin.historyScroller.table.header.requestPeriod,
    accessor,
    disableSortBy: true,
    id: COLUMN_NAMES.PERIOD_TYPE,
    isVisible: true,
    maxWidth: 220,
    minWidth: 130,
    width: 200,
  },
  {
    Cell: Format,
    Header: locale.admin.historyScroller.table.header.format,
    accessor,
    disableSortBy: true,
    id: COLUMN_NAMES.FORMAT,
    isVisible: true,
    maxWidth: 150,
    minWidth: 85,
    width: 120,
  },
  {
    Cell: RequestStatus,
    Header: locale.admin.historyScroller.table.header.requestStatus,
    accessor,
    id: COLUMN_NAMES.REQUEST_STATUS,
    isVisible: true,
    maxWidth: 250,
    minWidth: 160,
    width: 230,
  },
  {
    Cell: User,
    Header: locale.admin.historyScroller.table.header.user,
    accessor,
    id: COLUMN_NAMES.USER,
    isVisible: false,
    maxWidth: 350,
    minWidth: 200,
    width: 250,
  },
  {
    Cell: ServiceBranches,
    Header: locale.admin.historyScroller.table.header.serviceBranch,
    accessor,
    disableSortBy: true,
    id: COLUMN_NAMES.SERVICE_BRANCHES,
    isVisible: false,
    maxWidth: 300,
    minWidth: 150,
    width: 250,
  },
  {
    Cell: StatementType,
    Header: locale.admin.historyScroller.table.header.statementType,
    accessor,
    disableSortBy: true,
    id: COLUMN_NAMES.STATEMENT_TYPE,
    isVisible: false,
    maxWidth: 200,
    minWidth: 130,
    width: 180,
  },
  {
    Cell: StatementStatus,
    Header: locale.admin.historyScroller.table.header.statementStatus,
    accessor,
    disableSortBy: true,
    id: COLUMN_NAMES.STATEMENT_STATUS,
    isVisible: false,
    maxWidth: 210,
    minWidth: 140,
    width: 190,
  },
  {
    Cell: Actions,
    accessor,
    disableResizing: true,
    disableSortBy: true,
    id: COLUMN_NAMES.ACTIONS,
    isVisible: true,
    width: 100,
  },
]);
