/* eslint-disable */
// prettier-ignore
// This file is automatically generated by typings-for-css-modules.
// Don't change it directly!

declare namespace StylesScssModule {
  export interface IStylesScss {
    'bothReducedCell': string;
    'cell': string;
    'clickableRow': string;
    'condensedCell': string;
    'headerCell': string;
    'headerColumnDelimiter': string;
    'headerRow': string;
    'layoutScrollWrapper': string;
    'leftReducedCell': string;
    'rightReducedCell': string;
    'row': string;
    'scrollIconBox': string;
    'sortIconWrapper': string;
    'sortIconWrapperLeft': string;
    'sortIconWrapperRight': string;
    'sortIndex': string;
    'table': string;
    'tableBody': string;
    'tableWrapper': string;
  }
}

declare const StylesScssModule: StylesScssModule.IStylesScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StylesScssModule.IStylesScss;
};

export = StylesScssModule;
