/* eslint-disable */
// prettier-ignore
// This file is automatically generated by typings-for-css-modules.
// Don't change it directly!

declare namespace StylesScssModule {
  export interface IStylesScss {
    'borderedRow': string;
    'cell': string;
    'clickableRow': string;
    'collapsedRow': string;
    'groupingRow': string;
    'groupingRowByAccount': string;
    'headerCell': string;
    'headerColumnDelimiter': string;
    'headerRow': string;
    'headerRowWrapper': string;
    'layoutScrollWrapper': string;
    'placeholderOverlay': string;
    'portal': string;
    'scrollIconBox': string;
    'sortIconWrapper': string;
    'table': string;
    'tableBody': string;
    'tableWrapper': string;
    'toggleButton': string;
    'zLayerContainer': string;
    'zLayerControl': string;
    'zLayerFix': string;
    'zLayerFluid': string;
    'zLayerMessage': string;
    'zLayerModal': string;
    'zLayerSidebar': string;
    'zLayerSpecific_element': string;
    'zLayerSpecific_element_accent': string;
    'zLayerSubmenu': string;
    'zLayerTopline': string;
  }
}

declare const StylesScssModule: StylesScssModule.IStylesScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StylesScssModule.IStylesScss;
};

export = StylesScssModule;
