/** Тип запроса выписки. */
export enum TYPE {
  ONETIME = 'ONETIME',
  REGULAR = 'REGULAR',
  HIDDEN_VIEW = 'HIDDEN_VIEW',
  HIDDEN_EXPORT = 'HIDDEN_EXPORT',
  HIDDEN_PRINT = 'HIDDEN_PRINT',
  HIDDEN_PRINT_EXPORT_OSV = 'HIDDEN_PRINT_EXPORT_OSV',
}
