/* eslint-disable */
// prettier-ignore
// This file is automatically generated by typings-for-css-modules.
// Don't change it directly!

declare namespace StylesScssModule {
  export interface IStylesScss {
    'actionsRowButton': string;
    'captionRow': string;
    'captionRowText': string;
    'footer': string;
    'footerDropdownActions': string;
    'incomeNat': string;
    'natCurrencyHeader': string;
    'natCurrencyHeaderText': string;
    'outcomeNat': string;
    'rowActionButton': string;
  }
}

declare const StylesScssModule: StylesScssModule.IStylesScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StylesScssModule.IStylesScss;
};

export = StylesScssModule;
