/* eslint-disable */
// prettier-ignore
// This file is automatically generated by typings-for-css-modules.
// Don't change it directly!

declare namespace StyleScssModule {
  export interface IStyleScss {
    'container': string;
    'halfOption': string;
    'option': string;
    'optionsContainer': string;
    'zLayerContainer': string;
    'zLayerControl': string;
    'zLayerFix': string;
    'zLayerFluid': string;
    'zLayerMessage': string;
    'zLayerModal': string;
    'zLayerSidebar': string;
    'zLayerSpecific_element': string;
    'zLayerSpecific_element_accent': string;
    'zLayerSubmenu': string;
    'zLayerTopline': string;
  }
}

declare const StyleScssModule: StyleScssModule.IStyleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StyleScssModule.IStyleScss;
};

export = StyleScssModule;
