/* eslint-disable */
// prettier-ignore
// This file is automatically generated by typings-for-css-modules.
// Don't change it directly!

declare namespace CommonScssModule {
  export interface ICommonScss {
    'inputWidth': string;
    'linkFocusable': string;
  }
}

declare const CommonScssModule: CommonScssModule.ICommonScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: CommonScssModule.ICommonScss;
};

export = CommonScssModule;
