/* eslint-disable */
// prettier-ignore
// This file is automatically generated by typings-for-css-modules.
// Don't change it directly!

declare namespace StylesScssModule {
  export interface IStylesScss {
    'action': string;
    'rowActionButton': string;
    'rowActions': string;
    'scrollIcon': string;
    'status': string;
    'totalWrapper': string;
    'zLayerContainer': string;
    'zLayerControl': string;
    'zLayerDrag_n_drop': string;
    'zLayerFix': string;
    'zLayerFluid': string;
    'zLayerMessage': string;
    'zLayerModal': string;
    'zLayerSidebar': string;
    'zLayerSpecific_element': string;
    'zLayerSpecific_element_accent': string;
    'zLayerSubmenu': string;
    'zLayerTopline': string;
  }
}

declare const StylesScssModule: StylesScssModule.IStylesScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StylesScssModule.IStylesScss;
};

export = StylesScssModule;
